import DealerCards from "@components/DealerCards";
import Decisions from "@components/Decisions";
import Deck from "@components/Deck";
import MessageBox from "@components/MessageBox";
import PlayerCards from "@components/PlayerCards";
import { useBank } from "@hooks/useBank";
import { useDealer } from "@hooks/useDealer";
import { useDeck } from "@hooks/useDeck";
import { useGame } from "@hooks/useGame";
import { usePlayer } from "@hooks/usePlayer";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { currencies, addToBet, getBalance } = useBank();
  return (
    <>
      <Head>
        <title>Black Jack Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen  overflow-hidden bg-green-700 flex flex-col  justify-between">
        <div className="h-[10%] bg-gray-800 bg-opacity-50 flex justify-around items-center">
          <MessageBox />
        </div>
        <div className="h-[20%] flex justify-center items-start">
          <DealerCards />
        </div>
        <div className="h-[20%] flex  items-center">
          <Deck />
        </div>
        <div className="h-[20%] flex justify-center items-end">
          <PlayerCards />
        </div>
        <div className="h-[10%] flex p-1">
          <div className="p-5 px-6 xl:p-6 rounded-xl xl:px-8 h-full m-auto bg-green-900 items-center inline-flex space-x-4  xl:space-x-5">
            {currencies.map((currency) => {
              return currency.component({
                onClick: () => {
                  addToBet("player", currency.value);
                },
                disabled:
                  getBalance("player").bills[currency.name] > 0 ? false : true,
                count: getBalance("player").bills[currency.name],
              });
            })}
          </div>
        </div>
        <div className="h-[20%] p-5 xl:p-10 grid grid-cols-12 gap-5 w-full bg-green-800  bottom-0">
          <Decisions />
        </div>
      </div>
    </>
  );
};

export default Home;
