import BettingBoard from "@components/BettingBoard";
import DealerCards from "@components/DealerCards";
import Decisions from "@components/Decisions";
import Deck from "@components/Deck";
import MessageBox from "@components/MessageBox";
import PlayerCards from "@components/PlayerCards";
import { useBank } from "@hooks/useBank";
import { useDealer } from "@hooks/useDealer";
import { useDeck } from "@hooks/useDeck";
import { useGame } from "@hooks/useGame";
import { usePlayer } from "@hooks/usePlayer";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { motion } from "framer-motion";
import PlayerBoard from "@components/PlayerBoard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Black Jack Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        layout
        className="h-screen  overflow-hidden bg-green-700 flex flex-col  "
      >
        <div className="h-[10vh] bg-gray-800 bg-opacity-50 flex justify-around items-center">
          <MessageBox />
        </div>
        <DealerCards />
        <div className="h-[30vh] flex my-auto items-center">
          <Deck />
        </div>
        <PlayerBoard />
        <div className="h-[15vh] mt-auto p-5 xl:p-10 grid grid-cols-12  z-10 gap-5 w-full bg-green-800  bottom-0">
          <Decisions />
        </div>
      </motion.div>
    </>
  );
};

export default Home;
